spring:
  application:
    name: user-service

  datasource:
    # keep the in-memory DB alive and simple for dev
    url: jdbc:h2:mem:userdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    # ensures data.sql runs AFTER JPA creates tables (fixes table-not-found)
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

jwt:
  secret: M8/cbuMrPtqktMPd+LSFpgUz+crgaH3tTRjVPZS4fVc=
  issuer: OnlineBookStore
  expiration: 1800000

server:
  port: 8081

eureka:
  client:
    service-url:
      # trailing slash is usually fine, but common convention is without it
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    root: INFO
    org.springframework.security: TRACE
    com.cg.online.book.store.security: DEBUG
    org.springframework.cloud.config: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: WARN
  pattern:
    level:   "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-},user=%X{userId:-anon}]"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [${spring.application.name},%X{traceId:-},%X{spanId:-},user=%X{userId:-anon}] [%thread] %logger{36} - %msg%n"
    file:    "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [${spring.application.name},%X{traceId:-},%X{spanId:-},user=%X{userId:-anon}] [%thread] %logger{36} - %msg%n"
